#!/usr/bin/env python3

import click
import objection


@click.command()
@click.option("--password", required=True, help="The settings file password")
@click.argument("prefsin", type=click.File("rb"))
@click.argument("prefsout", type=click.File("wb"))
def objection_pass(password: str, prefsin: click.File, prefsout: click.File):
    """Pass the objectives in an AndroidAPS preferences file\n\n
    PREFSIN: The settings file input\n
    PREFSOUT: The settings file output"""
    outer_json, preferences, iv_sz, iv = objection.deserialize_settings(
        prefsin.read(), password
    )
    objection.pass_objectives(preferences)
    prefsout.write(
        objection.serialize_settings(outer_json, preferences, iv_sz, iv, password)
    )


if __name__ == "__main__":
    objection_pass()
