#!/usr/bin/env python3

import click
import code
import objection
import pprint

BANNER = """AndroidAPS interactive preference editor
========================================
Useful objects / functions:
  ppp(): pretty-print the preferences
  ppm(): pretty-print the metadata
  pps(): pretty-print the securitystuff
  preferences: the actual preferences
  outer_json: the enclosing obfuscationstuff
Ctrl-D to complete & write"""


@click.command()
@click.option("--password", required=True, help="The settings file password")
@click.argument("prefsin", type=click.File("rb"))
@click.argument("prefsout", type=click.File("wb"))
def objection_edit(password: str, prefsin: click.File, prefsout: click.File):
    """Interactively edit (REPL) an AndroidAPS preferences file\n\n
    PREFSIN: The settings file input\n
    PREFSOUT: The settings file output"""
    outer_json, preferences, iv_sz, iv = objection.deserialize_settings(
        prefsin.read(), password
    )

    def ppp():
        pprint.pprint(preferences)

    def ppm():
        pprint.pprint(outer_json["metadata"])

    def pps():
        pprint.pprint(outer_json["security"])

    code.interact(banner=BANNER, local=dict(globals(), **locals()))
    prefsout.write(
        objection.serialize_settings(outer_json, preferences, iv_sz, iv, password)
    )


if __name__ == "__main__":
    objection_edit()
